name: admob_flutter_example
description: Demonstrates how to use the admob_flutter plugin.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  pedantic: 1.11.0
  flutter_test:
    sdk: flutter

  admob_flutter:
    path: ../

flutter:
  uses-material-design: true
